export const ActionTypes = {
  GET_LISTINGS: 'GET_LISTINGS',
  CREATE_LISTING: 'CREATE_LISTING',
  GET_CHATS: 'GET_CHATS',
  CREATE_CHAT: 'CREATE_CHAT',
  SET_CHAT: 'SET_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  GET_MESSAGES: 'GET_MESSAGES',
  ADD_FRIEND: 'ADD_FRIEND',
  GET_FRIENDS: 'GET_FRIENDS',
}
